### PR TITLE
Enable to get impedance controller mode

### PR DESCRIPTION
**Pull request by snozawa**
ImpedanceControllerのモードが何になってるかをgetできるようにしました。
よろしくお願いします。

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1922/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1923/
Test PASSed.

**Comment by k-okada** [comment]
毎回同じ所でエラーになっているばあいは，そもそもエラーが有る可能性が高いです．
https://github.com/fkanehiro/hrpsys-base/pull/557 でしょうか．直してみました．

**Comment by k-okada** [comment]
つまり，だいぶ.travisなおしてロバストにしたつもりです．（この瞬間は）

**Comment by snozawa** [comment]
なるほど、ありがとうございます。
 #557の箇所だったのですね。（今回はあまりちゃんとエラーログをみてませんでした）

**Comment by snozawa** [comment]
masterをMergeしてみました

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1927/
Test PASSed.

**Comment by k-okada** [comment]
what is the default value of controller_mode?
is this ok?
```
    def startImpedance(self, arm,
                       M_p = 100.0,
                       D_p = 100.0,
                       K_p = 100.0,
                       M_r = 100.0,
                       D_r = 2000.0,
                       K_r = 2000.0,
                       force_gain = [1, 1, 1],
                       moment_gain = [0, 0, 0],
                       sr_gain = 1.0,
                       avoid_gain = 0.0,
                       reference_gain = 0.0,
                       manipulability_limit = 0.1,
                       controller_mode = OpenHRP::ControllerMode::MODE_IMP):
```

**Comment by snozawa** [comment]
The default value is `controller_mode = OpenHRP::ControllerMode::MODE_IDLE` because impedance controller is idle mode at the begening.

Is this related with `rtmros_common` travis error?
https://github.com/start-jsk/rtmros_common/pull/703#issuecomment-93279546

In order to set parameter, please do not create `OpenHRP.ImpedanceControllerService.impedanceParam` instsance directly.

In example codes, to create impedanceParam instance, 
we use `getImpedanceControllerParam` and modify it for `setImpedanceControllerParam`.
https://github.com/fkanehiro/hrpsys-base/blob/master/sample/SampleRobot/samplerobot_impedance_controller.py#L34

`ImpedanceControllerService_idl.py` is generated from idl file like this:
```
        def __init__(self, M_p, D_p, K_p, M_r, D_r, K_r, force_gain, moment_gain, sr_gain, avoid_gain, reference_gain, manipulability_limit, controller_mode):
```
Generated file does not use default argument.
So, if IDL file in upstream `hrpsys-base` is updated, we need to change all arguments for `OpenHRP.ImpedanceControllerService.impedanceParam` and everytime travis error occurs.

If we set impedanceparam like 
https://github.com/fkanehiro/hrpsys-base/blob/master/sample/SampleRobot/samplerobot_impedance_controller.py#L34, we do not need to upstream hrpsys-base change 
and travis can pass without any downstream change.


In addition, how about this?
```
def setImpedanceControllerParam(self, arm, M_p = None,...)
   icp = self.ic_svc.getImpedanceControllerParam(arm)
   if M_p != None:
      icp.M_p = M_p
   ....
```
In current hironx startImpedance, all parameters are overwritten by default argument, 
even if user want to overwrite only M_p and use default value for other parameter.
https://github.com/start-jsk/rtmros_hironx/blob/hydro-devel/hironx_ros_bridge/src/hironx_ros_bridge/hironx_client.py#L732
If we use argument like `M_p = None`, user can overwrite only M_p and use default value for other parameter.

If developers define recommended parameter tuned for hironx in `hironx_client.py`, please wrap the function:
```
def setImpedanceControllerParamCommon(self, arm, M_p = None,...)
   icp = self.ic_svc.getImpedanceControllerParam(arm)
   if M_p != None:
      icp.M_p = M_p
   ....

def setImpedanceControllerParam(self, arm, M_p = 100.0, ...) # <= recommended parameter
   self.setImpedanceControllerParam(arm, M_p = M_p, ...)
```

In euslisp interface, I implemented above-mentioned arguments passing and using of get-and-set parameters:
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L247
In many cases, we do not care about upstream `hrpsys-base` in downstream euslisp interface file for ImpedanceController, AutoBalancer, Stabilizer, and KalmanFilter.

**Comment by k-okada** [comment]
so , do you think we should prepare 4 methods like:

startImpedanceController()
stopImpedanceController()
setImpedanceCotrollerParam()
getImpedanceControllerParam()

in

https://github.com/k-okada/rtmros_hironx/commit/330175fb1e492e1077dcd9bd9a5aa9ec032dc1f4

I wrote statImepedance and that calls both setImpedanceControllerParam and
statImpedanceController()
but it is not what you expected?

anyway I think we'd better to add default *ImpedanceControlelr*() method in
hrpsys_config.py, do you already have code for that?

--
◉ Kei Okada

**Comment by snozawa** [comment]
> so , do you think we should prepare 4 methods like:

Yes. I think so, but

>  I wrote statImepedance and that calls both setImpedanceControllerParam and statImpedanceController() but it is not what you expected?

You can implement startImpedance like this:
```
def startImpedanceControllerOrg (...):
   self.hc_svc.startImpedanceController(...)

def startImpedaneController (self, arm, ...):
   self.setImpedanceControllerParam()
   self.startImpedanceController(...)
```
It is for backward compatibility, because `startImpedance` is previously written by `setImpedaceController` few month ago.
In euslisp interface, we are doing so, but recently i think it would be better to remove `setImpedanceParam` from `startImpedance` to keep consistency with IDL file.
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L451

> anyway I think we'd better to add default *ImpedanceControlelr*() method in hrpsys_config.py, do you already have code for that?

Yes, for start and stop function, we have that code, but I did not move this code to `hrpsys_config.py`.
```
 def startImpedanceController(self):
   self.ic_svc.startImpedanceController("larm")
   self.ic_svc.startImpedanceController("rarm")
def stopImpedanceController(self):
   self.ic_svc.stopImpedanceController("larm")
   self.ic_svc.stopImpedanceController("rarm")
```

For set and get parameter functions (for several RTCs), I have not implemented yet.

I'd like to implement set parameter function by using set + get function as mentioned in 
https://github.com/fkanehiro/hrpsys-base/pull/555#issuecomment-93579403.
```
def setXXparam (self, param1 = None,...):
   prm=self.getXXparam()
   if param1 != None:
       prm.param1 = param1
   ...
   self.xx_svc.setXXParam(prm)
```
To achieve this code, we need to modify setXXparam arguments when we add new parameter to IDL file.

Or, if we can generate arguments from python interface of IDL file,
we do not need to change setXXparam argument when we add new parameter to IDL file.
In euslisp code, arguments of `:set-xx-param` is generated from idl files (srv file) and 
`:set-xx-param` method is defined by macro.
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L247
However, I'm not so familiar with python coding and I did not know how to write such codes in python.

**Pull request merged**
