### PR TITLE
[doc][py] Elaborate methods (playPattern*, setTarget*, startImpedance)

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2829/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2830/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2831/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2832/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2833/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2834/
Test PASSed.

**Comment by 130s** [comment]
Re-triggering travis

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2850/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2851/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2856/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2857/
Test PASSed.

**Comment by k-okada** [comment]
LGTM


単なんる興味ですが、
+ This only includes the time taken for execution
 +                         (i.e. time for planning and other misc.
processes are considered).
は、この説明が必要なシチュエーションはどういう状況でしょうか．実際にplanningに時間がかかっている？



--
◉ Kei Okada


2017-05-10 0:53 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by 130s** [comment]
>+ This only includes the time taken for execution + (i.e. time for planning and other misc. processes are considered).

まず，大事な間違いをしていたので commit を更新しました．

- x `i.e. time for planning and other misc. processes are considered).`
- o `i.e. time for planning and other misc. processes are not considered).`

この説明が特に必要だった状況が思い出せてませんが，はっきりさせたかった，くらいではないかと思います．

Commit msg https://github.com/fkanehiro/hrpsys-base/pull/1120/commits/37253752477193ce97f9277844c768bfcb1f78d1 を見ると一応 `SequencePlayer` のコード上 `tm` は planning には係らず execution のみに係るようなのは確認したようですが，そもなぜ必要と思ったのかは書いてないですね．まあ初心者ユーザにとっては，一つのコマンド内で planning と execution が実行されているということはあまり分からないので，使ってるうちに気になった時のため等に文書化しておくのは悪くないかと．

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2860/
Test PASSed.

**Pull request merged**
