### PR TITLE
add sample and test for ReferenceForceUpdater

### PR DESCRIPTION
**Pull request by mmurooka**
ReferenceForceUpdaterのサンプルとテストを追加しました．
https://github.com/fkanehiro/hrpsys-base/pull/996#issuecomment-222042356

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2647/
Test PASSed.

**Comment by snozawa** [comment]
LGTM

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2649/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2650/
Test PASSed.

**Comment by mmurooka** [comment]
テスト通りましたのでお手すきのときにmergeお願い致します．

**Pull request merged**
