### PR TITLE
add service for changing collision loop

### PR DESCRIPTION
**Pull request by yswhynot**

### CODE REVIEW

**Comment by k-okada** [comment]
Thanks @yswhynot . Can you revert .gitignore, because that is not directory related to this PR, sorry for picky.

**Comment by yswhynot** [comment]
@k-okada Hi I've updated the commit. Pls check :)

**Comment by k-okada** [comment]
I think this is ok to merge @fkanehiro

**Comment by k-okada** [comment]
@fkanehiro すいません間違い．ちょっと待って下さい．

**Comment by k-okada** [comment]
@yswhynot I have found your CollisionDetector.cpp has so many diffs, and if I checked your diffs ignoring white spaces and cerated another PR at #1175, I also removed `(input_loop < 50)`, is it ok? 
```
$ diff -w CollisionDetector.cpp CollisionDetector.cpp.org 
450,453c450
< 						for ( unsigned int i = 0; i < jointPath->numJoints(); i++ ){ 
< 							if ( m_init_collision_mask[jointPath->joint(i)->jointId] == 1) 
< 								stop_all = false; 
< 						}
---
>                         for ( unsigned int i = 0; i < jointPath->numJoints(); i++ ){ if ( m_init_collision_mask[jointPath->joint(i)->jointId] == 1) stop_all = false; }
705,712d701
< bool CollisionDetector::setCollisionLoop(int input_loop) {
< 	if ((input_loop > 0) && (input_loop < 50)) {
< 		m_collision_loop = input_loop;
< 		return true;
< 	}
< 	return false;
< }
< 
```

**Comment by yswhynot** [comment]
@k-okada Sure it's ok :) 
Sorry for the tabs coz I accidentally pressed auto format in my editor and find it impossible to go back...

**Comment by k-okada** [comment]
@yswhynot ok, so please close this issue

**Pull request closed without merging**
