### PR TITLE
[PDcontroller] initialize reference angle with current angle at onActevated()

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
see https://github.com/fkanehiro/hrpsys-base/issues/761

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2263/
Test PASSed.

**Comment by YoheiKakiuchi** [comment]
DO NOT MERGE YET

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2264/
Test PASSed.

**Comment by YoheiKakiuchi** [comment]
Please merge.

**Pull request merged**
