### PR TITLE
use 0x... format instead of binary format 0b...

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2410/

**Build Log**
*last 10 lines*

 ```
[...truncated 3543 lines...]
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

Test FAILed.

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2411/console
で再確認中

**Comment by k-okada** [comment]
@snozawa please review, https://github.com/fkanehiro/hrpsys-base/pull/854 did not work for QNX
and this closes https://github.com/fkanehiro/hrpsys-base/issues/868

**Comment by snozawa** [comment]
LGTM.
This PR does not use binary format and this seems to work both on old system and new system.

**Comment by k-okada** [comment]
@fkanehiro マージお願いします

--
◉ Kei Okada

2015/10/29 20:06、Shunichi Nozawa <notifications@github.com> のメッセージ:

**Pull request merged**
