### PR TITLE
[ModifiedServo] Create InPorts and OutPorts for pdgains

### PR DESCRIPTION
**Pull request by rohanpsingh**
I tested this in simulation and it works as expected.

Even though my application doesn't require it, but maybe we should also add ports for reading the current gains?

### CODE REVIEW

**Comment by fkanehiro** [comment]
@rafaelxero Please check.

**Comment by rohanpsingh** [comment]
If you would like to try it out with mc_openrtm,
this branch creates a [datastore make_call](https://jrl-umi3218.github.io/mc_rtc/tutorials/recipes/datastore.html):
https://github.com/rohanpsingh/mc_openrtm/tree/topic/servo-pdgains-call 
which can be called from any mc-rtc controller.

**Comment by rohanpsingh** [comment]
I created port to _read_ the PD gains too. And consequently, the registered names are now `*gainsSet` and `*gainsGet`.  

@rafaelxero @fkanehiro 
Could you also please comment on whether it's safe to allow setting P gains and D gains separately?
Would it be better to only have one port with a `TimedDoubleSeq` that's a concatenation of kp vector and kd vector?

**Comment by rafaelxero** [comment]
Thank you @rohanpsingh, I think it is OK
You can merge

**Pull request merged**
