### PR TITLE
Add c++ 11 support, and lock sequence player

### LINKED ISSUE #836: Sequence Player crash on seq_svc.clear()
I am currently experimenting with choreonoid to check that my generated motions are correct. I play them in choreonoid using the Sequence Player. Those motions are quite long, thus I often call seq_svc.clear() to stop them and start another without having to close choreonoid and restart.

Once in a while, choreonoid crashes, when calling interpolator::pop_back() on a "double free or corruption".
```
#3  0x00007ffff5f9c66e in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff609ec10 "double free or corruption (!prev)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fffb44bb231 in interpolator::pop_back() () from /usr/local/lib/SequencePlayer.so
#6  0x00007fffb44bdc8e in seqplay::pop_back() () from /usr/local/lib/SequencePlayer.so
#7  0x00007fffb44bdd48 in seqplay::clear(double) () from /usr/local/lib/SequencePlayer.so
```

Full backtrace here:  https://gist.github.com/haudren/d02a602ca9212d37d6ef

I think that in some cases, we are trying to pop the top element from the interpolator, but due to timing, another instance of pop_back is currently executing (and gets the same pointer to the back element), and thus we try to delete twice the same element.

Any ideas ?

Thank you,
Hervé

### PR DESCRIPTION
**Pull request by haudren**
Hello,

This is a pull request that does two things:
- Fix #836 by using mutex
- Switch to C++11

I switched to C++11 to be able to use the std::lock_guard construct. I know that upgrading to C++11 may pose problem to some users, especially if their robots still use older versions of Ubuntu. I do not know about JSK ( @k-okada ) or other labs. 

This efficiently solves the problem for the Sequence Player, I was able to clear and restart the sequence more than 10 times in row without crash.

For the C++11 port, it was just a matter of removing ambiguous calls to isnan/isinf and boost::assign plus adding a constexpr were necessary.

Please tell me your opinion,
Hervé

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2379/

**Build Log**
*last 10 lines*

 ```
[...truncated 7144 lines...]
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

Test FAILed.

**Comment by k-okada** [comment]
Great !

It would help up if you add #ifdef macro for switching latest system and old one. Our JAXON robot can use latest OS but we still uses 8.04 OS for our HRP2 and also using QNX for Hiro robot.
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2379/console

```
make[2]: Leaving directory `/tmp/hrpsys-source-837-2015-10-01/build'
make -f idl/CMakeFiles/hrpsysBaseStub.dir/build.make idl/CMakeFiles/hrpsysBaseStub.dir/build
make[2]: Entering directory `/tmp/hrpsys-source-837-2015-10-01/build'
/usr/pkg/bin/cmake -E cmake_progress_report /tmp/hrpsys-source-837-2015-10-01/build/CMakeFiles 
[  8%] Generating DataLoggerService.hh, DataLoggerServiceSk.cpp, DataLoggerServiceDynSk.cpp
cd /tmp/hrpsys-source-837-2015-10-01/build/idl && omniidl -bcxx -Wbuse_quotes -Wbh=.hh -Wbs=Sk.cpp -Wba -Wbd=DynSk.cpp -I/opt/jsk/include/openrtm-1.1/rtm/idl /tmp/hrpsys-source-837-2015-10-01/src/hrpsys-base-837/idl/DataLoggerService.idl
/usr/pkg/bin/cmake -E cmake_progress_report /tmp/hrpsys-source-837-2015-10-01/build/CMakeFiles 
[  8%] Building CXX object idl/CMakeFiles/hrpsysBaseStub.dir/DataLoggerServiceSk.o
cd /tmp/hrpsys-source-837-2015-10-01/build/idl && /usr/qnx650/host/qnx6/x86/usr/bin/QCC  -x c++ -DhrpsysBaseStub_EXPORTS -DROBOT_IOB_VERSION=2 -I/usr/pkg/include;-std=c++11 -O3 -DNDEBUG -I/usr/local/include -I/opt/jsk/include -I/usr/pkg/include -I/tmp/hrpsys-source-837-2015-10-01/src/hrpsys-base-837/../../include -I/opt/jsk/include/coil-1.1 -I/opt/jsk/include/openrtm-1.1 -I/opt/jsk/include/openrtm-1.1/rtm/idl -I/opt/jsk/include/OpenHRP-3.1 -I/opt/jsk/include/eigen3 -I/tmp/hrpsys-source-837-2015-10-01/src/hrpsys-base-837/lib -I/tmp/hrpsys-source-837-2015-10-01/build/idl   -DHRPSYS_PACKAGE_VERSION="\"315.7.0\"" -o CMakeFiles/hrpsysBaseStub.dir/DataLoggerServiceSk.o -c /tmp/hrpsys-source-837-2015-10-01/build/idl/DataLoggerServiceSk.cpp
cc: no files to process
/bin/sh: -std=c++11: cannot execute - No such file or directory
make[2]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/DataLoggerServiceSk.o] Error 126
make[2]: Leaving directory `/tmp/hrpsys-source-837-2015-10-01/build'
make[1]: *** [idl/CMakeFiles/hrpsysBaseStub.dir/all] Error 2
make[1]: Leaving directory `/tmp/hrpsys-source-837-2015-10-01/build'
make: *** [all] Error 2
=====
$ tar -xvzf /tmp/hrpsys-837-qnx-
```

**Comment by garaemon** [comment]
`-std=c11` is only available from gcc-4.7.
ubuntu 12.04 uses gcc 4.6 as default and it would be difficult to compile with older version of gcc.

http://stackoverflow.com/questions/16256586/how-to-enable-c11-on-later-versions-of-gcc

**Comment by haudren** [comment]
I just made a pull request #839 that avoids relying on newer C++ constructs. If people are interested in getting a C++11 makeover of hrpsys-base, we can do so here but I think it would be better to wait until we could compile it on most robots.

**Pull request closed without merging**
