### PR TITLE
added lock to prevent multithread access to waitInterpolationOfGroup

### PR DESCRIPTION
**Pull request by emijah**
Found that waitInterpolationOfGroup freezes when accessed when it is waiting on another group. Added a lock to the python interface to only wait on one group at a time.

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1973/
Test PASSed.

**Comment by k-okada** [comment]
please rebase origin/master to pass the test

question: is waitInterpolationOfGroup only function that causes deadlock?

**Comment by emijah** [comment]
Okay, will do, however, more checking is probably required.
I've a feeling there may be problems if you call set*OfGroup functions, with the same group from different threads. I think I need to add a test script

**Comment by emijah** [comment]
がー。改悪してしまった。やり直します。

**Pull request closed without merging**
