### PR TITLE
rtm.py : fix wrong commit on #634 (isConnected() and False: )

### PR DESCRIPTION
**Pull request by k-okada**
#634

### CODE REVIEW

**Comment by k-okada** [comment]
さすがに今日は無理だけど、頑張ってテスト作ろうと思うのでマージはちょっと待って下さい

**Comment by 130s** [comment]
+1
Confirmed with NEXTAGE Open (simulation) that this fixes the issue #979

```
$ rtcat -l localhost:15005/sh.rtc | grep Connect | uniq -c
      1  +Connected to  /localhost:15005/HiroNX(Robot)0.rtc:q
      1  +Connected to  /localhost:15005/seq.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:tqRef
      1  +Connected to  /localhost:15005/seq.rtc:basePos
      1  +Connected to  /localhost:15005/seq.rtc:baseRpy
      1  +Connected to  /localhost:15005/seq.rtc:zmpRef
      1  +Connected to  /localhost:15005/seq.rtc:optionalData
      1  +Connected to  /localhost:15005/el.rtc:qRef
      1  +Connected to  /localhost:15005/fk.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:qInit
      1  +Connected to  /localhost:15005/log.rtc:sh_qOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:qRef
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:mcangle
      1  +Connected to  /localhost:15005/log.rtc:sh_tqOut
      1  +Connected to  /localhost:15005/seq.rtc:basePosInit
      1  +Connected to  /localhost:15005/fk.rtc:basePosRef
      1  +Connected to  /localhost:15005/log.rtc:sh_basePosOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:basePosIn
      1  +Connected to  /localhost:15005/seq.rtc:baseRpyInit
      1  +Connected to  /localhost:15005/fk.rtc:baseRpyRef
      1  +Connected to  /localhost:15005/log.rtc:sh_baseRpyOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:baseRpyIn
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:baseTform
      1  +Connected to  /localhost:15005/seq.rtc:zmpRefInit
      1  +Connected to  /localhost:15005/log.rtc:sh_zmpOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/StateHolderServiceROSBridge.rtc:StateHolderService

(ran `rosrun nextage_ros_bridge nextage.py`)
$ rtcat -l localhost:15005/sh.rtc | grep Connect | uniq -c
      1  +Connected to  /localhost:15005/HiroNX(Robot)0.rtc:q
      1  +Connected to  /localhost:15005/seq.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:tqRef
      1  +Connected to  /localhost:15005/seq.rtc:basePos
      1  +Connected to  /localhost:15005/seq.rtc:baseRpy
      1  +Connected to  /localhost:15005/seq.rtc:zmpRef
      1  +Connected to  /localhost:15005/seq.rtc:optionalData
      1  +Connected to  /localhost:15005/el.rtc:qRef
      1  +Connected to  /localhost:15005/fk.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:qInit
      1  +Connected to  /localhost:15005/log.rtc:sh_qOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:qRef
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:mcangle
      1  +Connected to  /localhost:15005/log.rtc:sh_tqOut
      1  +Connected to  /localhost:15005/seq.rtc:basePosInit
      1  +Connected to  /localhost:15005/fk.rtc:basePosRef
      1  +Connected to  /localhost:15005/log.rtc:sh_basePosOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:basePosIn
      1  +Connected to  /localhost:15005/seq.rtc:baseRpyInit
      1  +Connected to  /localhost:15005/fk.rtc:baseRpyRef
      1  +Connected to  /localhost:15005/log.rtc:sh_baseRpyOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:baseRpyIn
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:baseTform
      1  +Connected to  /localhost:15005/seq.rtc:zmpRefInit
      1  +Connected to  /localhost:15005/log.rtc:sh_zmpOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/StateHolderServiceROSBridge.rtc:StateHolderService

(ran `ipython -i `rospack find nextage_ros_bridge`/script/nextage.py`)
$ rtcat -l localhost:15005/sh.rtc | grep Connect | uniq -c
      1  +Connected to  /localhost:15005/HiroNX(Robot)0.rtc:q
      1  +Connected to  /localhost:15005/seq.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:tqRef
      1  +Connected to  /localhost:15005/seq.rtc:basePos
      1  +Connected to  /localhost:15005/seq.rtc:baseRpy
      1  +Connected to  /localhost:15005/seq.rtc:zmpRef
      1  +Connected to  /localhost:15005/seq.rtc:optionalData
      1  +Connected to  /localhost:15005/el.rtc:qRef
      1  +Connected to  /localhost:15005/fk.rtc:qRef
      1  +Connected to  /localhost:15005/seq.rtc:qInit
      1  +Connected to  /localhost:15005/log.rtc:sh_qOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:qRef
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:mcangle
      1  +Connected to  /localhost:15005/log.rtc:sh_tqOut
      1  +Connected to  /localhost:15005/seq.rtc:basePosInit
      1  +Connected to  /localhost:15005/fk.rtc:basePosRef
      1  +Connected to  /localhost:15005/log.rtc:sh_basePosOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:basePosIn
      1  +Connected to  /localhost:15005/seq.rtc:baseRpyInit
      1  +Connected to  /localhost:15005/fk.rtc:baseRpyRef
      1  +Connected to  /localhost:15005/log.rtc:sh_baseRpyOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/ic.rtc:baseRpyIn
      1  +Connected to  /localhost:15005/HrpsysSeqStateROSBridge0.rtc:baseTform
      1  +Connected to  /localhost:15005/seq.rtc:zmpRefInit
      1  +Connected to  /localhost:15005/log.rtc:sh_zmpOut
      1  +Connected to  /localhost:15005/tork-kudu1.host_cxt/manager.mgr/StateHolderServiceROSBridge.rtc:StateHolderService
```

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2602/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2603/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2604/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2605/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2606/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2607/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2608/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2609/
Test PASSed.

**Comment by k-okada** [comment]
@fkanehiro 期待通りのテストコード＋修正コードがコミットできました

**Pull request merged**
