### PR TITLE
Install SampleRobot python scripts and comment out symbolic links to avoid duplication

### PR DESCRIPTION
**Pull request by chiwunau**
I am not sure about the reason of creating symbolic link of ./idl and ./samples, but it leads to duplication when let say rosrun hrpsys *.py

### CODE REVIEW

**Comment by k-okada** [comment]
Please do not merge, I'll fix this

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1961/
Test PASSed.

**Comment by k-okada** [comment]
I think
```
file(GLOB python_scripts RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.py")
install(PROGRAMS ${python_scripts} DESTINATION share/hrpsys/samples/SampleRobot)
```
is ok, could fix PR, 

use rebase->squash to clean up commit -> http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by chiwunau** [comment]
fixed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1970/
Test PASSed.

**Comment by k-okada** [comment]
you do not have to modify CMakeList.txt, and only add two line https://github.com/fkanehiro/hrpsys-base/pull/581#issuecomment-93739818 in  sample/SampleRobot/CMakeLists.txt, also please remove white lines.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1971/
Test PASSed.

**Comment by chiwunau** [comment]
fixed as @k-okada told.
However, after merged the origin/master
when rosrun hrpsys samplerobot_walk.py, comes the following error
```
au@au-ThinkPad-T440p:~$ rosrun hrpsys samplerobot_walk.py 
[rosrun] You have chosen a non-unique executable, please pick one of the following:
1) /home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
2) /home/au/ros/hydro_parent/devel/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
3) /home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
4) /home/au/ros/hydro_parent/devel/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
5) /home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
6) /home/au/ros/hydro_parent/devel/share/hrpsys/samples/SampleRobot/samplerobot_walk.py
#? 1
configuration ORB with au-ThinkPad-T440p:15005
[hrpsys.py] waiting ModelLoader
[hrpsys.py] start hrpsys
[hrpsys.py] finding RTCManager and RobotHardware
[hrpsys.py] wait for RTCmanager : None
[hrpsys.py] wait for SampleRobot(Robot)0 : <hrpsys.rtm.RTcomponent instance at 0x21ca998> ( timeout 0 < 10)
[hrpsys.py] findComps -> RobotHardware : <hrpsys.rtm.RTcomponent instance at 0x21ca998> isActive? = True 
[hrpsys.py] simulation_mode : True
[hrpsys.py] creating components
[hrpsys.py]   eval : [self.seq, self.seq_svc, self.seq_version] = self.createComp("SequencePlayer","seq")
RTC named "seq" already exists.
[hrpsys.py] create Comp -> SequencePlayer : <hrpsys.rtm.RTcomponent instance at 0x21d5dd0> (315.3.0)
[hrpsys.py] create CompSvc -> SequencePlayer Service : <OpenHRP._objref_SequencePlayerService instance at 0x21db638>
[hrpsys.py]   eval : [self.sh, self.sh_svc, self.sh_version] = self.createComp("StateHolder","sh")
RTC named "sh" already exists.
[hrpsys.py] create Comp -> StateHolder : <hrpsys.rtm.RTcomponent instance at 0x21d5050> (315.3.0)
[hrpsys.py] create CompSvc -> StateHolder Service : <OpenHRP._objref_StateHolderService instance at 0x21e0e18>
[hrpsys.py]   eval : [self.fk, self.fk_svc, self.fk_version] = self.createComp("ForwardKinematics","fk")
RTC named "fk" already exists.
[hrpsys.py] create Comp -> ForwardKinematics : <hrpsys.rtm.RTcomponent instance at 0x1f89638> (315.3.0)
[hrpsys.py] create CompSvc -> ForwardKinematics Service : <OpenHRP._objref_ForwardKinematicsService instance at 0x21e37e8>
[hrpsys.py] connecting components
('sh.qOutandHGcontroller0.qIn', 'are already connected')
('HGcontroller0.qOutandSampleRobot(Robot)0.qRef', 'are already connected')
('SampleRobot(Robot)0.qandsh.currentQIn', 'are already connected')
('SampleRobot(Robot)0.qandfk.q', 'are already connected')
('sh.qOutandfk.qRef', 'are already connected')
('seq.qRefandsh.qIn', 'are already connected')
('seq.tqRefandsh.tqIn', 'are already connected')
('seq.basePosandsh.basePosIn', 'are already connected')
('seq.baseRpyandsh.baseRpyIn', 'are already connected')
('seq.zmpRefandsh.zmpIn', 'are already connected')
('seq.optionalDataandsh.optionalDataIn', 'are already connected')
('sh.basePosOutandseq.basePosInit', 'are already connected')
('sh.basePosOutandfk.basePosRef', 'are already connected')
('sh.baseRpyOutandseq.baseRpyInit', 'are already connected')
('sh.baseRpyOutandfk.baseRpyRef', 'are already connected')
('sh.qOutandseq.qInit', 'are already connected')
('sh.zmpOutandseq.zmpRefInit', 'are already connected')
[hrpsys.py] activating components
seqis already serialized
shis already serialized
fkis already serialized
[hrpsys.py] setup logger
[hrpsys.py]   setupLogger : self.log is not defined, please check rtcd.conf or rtcd arguments
[hrpsys.py] setup joint groups
[hrpsys.py] initialized successfully
Traceback (most recent call last):
  File "/home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py", line 38, in <module>
    demo()
  File "/home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py", line 35, in demo
    loadPattern("$(OPENHRP_DIR)/share/OpenHRP-3.1/sample/controller/SampleController/etc/Sample")
  File "/home/au/ros/hydro_parent/devel/share/hrpsys/share/hrpsys/samples/SampleRobot/samplerobot_walk.py", line 30, in loadPattern
    hcf.loadPattern(basename, tm)
  File "/home/au/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py", line 1000, in loadPattern
    return self.seq_svc.loadPattern(fname, tm)
  File "/home/au/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/SequencePlayerService_idl.py", line 155, in loadPattern
    return _omnipy.invoke(self, "loadPattern", _0_OpenHRP.SequencePlayerService._d_loadPattern, args)
omniORB.CORBA.BAD_PARAM: CORBA.BAD_PARAM(omniORB.BAD_PARAM_WrongPythonType, CORBA.COMPLETED_NO)

```

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1972/
Test PASSed.

**Comment by k-okada** [comment]
try compile after `rm -fr`
and make sure that you
have /home/au/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/SequencePlayerService_idl.py

also make sure that
your  /home/au/ros/hydro_parent/devel/lib/python2.7/dist-packages/hrpsys/hrpsys_config.py
is same version as
https://github.com/fkanehiro/hrpsys-base/blob/master/python/hrpsys_config.py#L671



--
◉ Kei Okada

**Comment by chiwunau** [comment]
I tried catkin clean --all then catkin b
and I also have to latest version of those files
but the same error stll occurs.

**Comment by k-okada** [comment]
taken over by https://github.com/fkanehiro/hrpsys-base/pull/592

**Comment by k-okada** [comment]
I see, the problem is 
0be6641#diff-6c33bc3d5bb515b220c1b7d93821cd9dR668, install multiple place is ok, one is for hrpsys and on is for ros convention.

**Comment by chiwunau** [comment]
I see, thank you.

**Comment by k-okada** [comment]
please close this issue

**Pull request closed without merging**
