### PR TITLE
[RobotHardware/robot.c] fix loading gain file, just ignore empty and # started line

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
allowing empty line and a line started with '#' for gain file

https://github.com/fkanehiro/hrpsys-base/pull/1249
https://github.com/s-kajita/hrpsys-base/issues/1

### CODE REVIEW

**Comment by s-kajita** [comment]
Please merge this pull request!

**Comment by fkanehiro** [comment]
I can't merge yet because some of tests are failing.

**Comment by s-kajita** [comment]
The build on Travis CI fails when ROS_DISTRO=hydro.
It passes when ROS_DISTRO=indigo and kinetic.
Why??

**Comment by k-okada** [comment]
please look into travis log to find the reason

--
◉ Kei Okada


2018-08-07 10:37 GMT+09:00 Shuuji Kajita <notifications@github.com>:

**Comment by YoheiKakiuchi** [comment]
Here is the cause of error in travis.
~~~
++ sudo apt-get install -qq -y ros-hydro-openhrp3
E: Unable to correct problems, you have held broken packages.
+++ error
~~~
Then, I tested in my docker.

~~~
$ aptitude install ros-hydro-openhrp3

The following packages have unmet dependencies:
 python-catkin-pkg-modules : Depends: python:any (>= 2.7.5-5~) which is a virtual package.
~~~

~~~
$ apt-cache show python-catkin-pkg-modules

Package: python-catkin-pkg-modules
Version: 0.4.7-1
Architecture: all
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 242
Depends: python-argparse, python-dateutil, python-docutils, python-pyparsing, python:any (<< 2.8), python:any (>= 2.7.5-5~)
~~~

Version of python in 12.04 is 2.7.3
~~~
$ aptitude show python

Version: 2.7.3-0ubuntu2.2
~~~

So, cause of this problem is that dependancy of python-catkin-pkg-modules was changed.
I will continue to find out the problem.

**Comment by YoheiKakiuchi** [comment]
https://github.com/ros-infrastructure/catkin_pkg/issues/232
fixed for building hydro

Please merge

**Comment by s-kajita** [comment]
I confirmed the updated code on our robot.
Thank you very much, Kakiuchi-sensei!!

**Comment by ishiguroJSK** [comment]
Is this problem really fixed?
In my environment, a test gain file like
```
80000 200 1000 10
80000 200 1000 10
80000 200 1000 10
80000 200 1000 10
80000 200 1000 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
80000 0 200 0 1000 0 10
```
was read as
```
dof = 12
[RobotHardware] loadGain
[RobotHardware]   RLEG_JOINT0, pgain = 80000, dgain = 1000, tqpgain = 0, tqdgain = 0
[RobotHardware]   RLEG_JOINT1, pgain = 80000, dgain = 1000, tqpgain = 0, tqdgain = 0
[RobotHardware]   RLEG_JOINT2, pgain = 80000, dgain = 1000, tqpgain = 0, tqdgain = 0
[RobotHardware]   RLEG_JOINT3, pgain = 80000, dgain = 1000, tqpgain = 0, tqdgain = 0
[RobotHardware]   RLEG_JOINT4, pgain = 80000, dgain = 1000, tqpgain = 0, tqdgain = 0
[RobotHardware]   RLEG_JOINT5, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT0, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT1, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT2, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT3, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT4, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
[RobotHardware]   LLEG_JOINT5, pgain = 80000, dgain = 200, tqpgain = 1000, tqdgain = 10
set_number_of_joints 12
choreonoid IOB will open
```

I searched and found out `std::istringstream` must ignore " " (space charactor).
https://www.tetsis.com/blog/?p=161
So, I think 
```
sstrm >> tmp; // dummy
```
line is not needed.

**Comment by YoheiKakiuchi** [comment]
There is no documentation for specification of gains.

From the source file, specification of a gain file as below
and a blank line is allowed
~~~
pgain 0 dgain
~~~

By this PR, specification of gain file as below.
~~~
# comment
pgain 0 dgain 0 tq_pgain 0 tq_dgain
~~~

[0 dgain], [0 tq_pgain] and [0 tq_dgain] are optional by this PR.
But dummy 0(any number are allowed) is required for backward compatibility.

Then, this behavior is an expected behavior.
@ishiguroJSK What did you expected ?

**Comment by ishiguroJSK** [comment]
I expected the file means
`pgain igain dgain`
, and for torque control, the file will be
`pgain igain dgain tq_pgain tq_dgain`
or
`pgain igain dgain tq_pgain tq_igain tq_dgain`.

But if there is such a reason, I'll follow as you said.

> But dummy 0(any number are allowed) is required for backward compatibility.

Just out of curiosity, you mean some legacy systems are using "0" for something like separator?

**Pull request merged**
