### PR TITLE
Use ccache to speed-up compilation on travis

### PR DESCRIPTION
**Pull request by garaemon**
Hope it works

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2465/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2466/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2468/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2469/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2472/
Test PASSed.

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2473/
Test PASSed.

**Comment by garaemon** [comment]
The features described here are currently only available for private repositories on travis-ci.com and our new container-based infrastructure.


cache is not available on current configuration...

**Pull request closed without merging**
