### PR TITLE
fix header file to pass qnx

### PR DESCRIPTION
**Pull request by eisoku9618**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2295/

**Build Log**
*last 10 lines*

 ```
[...truncated 7073 lines...]
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
```

Test FAILed.

**Comment by eisoku9618** [comment]
No space left on device のようです．

**Comment by snozawa** [comment]
すいません、ありがとう。

**Comment by eisoku9618** [comment]
``git commit --amend``で jenkins が restart するかテスト

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2299/
Test PASSed.

**Comment by eisoku9618** [comment]
travis & jenkins passed!

**Pull request merged**
