### PR TITLE
line break

### PR DESCRIPTION
**Pull request by eisoku9618**

### CODE REVIEW

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1858/

**Build Log**
*last 10 lines*

 ```
[...truncated 2145 lines...]
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

Test FAILed.

**Comment by eisoku9618** [comment]
ここに改行が入らないと，例えば以下のように出力が見づらくなってしまう気がします．

```bash
CAUTION!! The robot is moving while collision detection!!!, since we do not get safe_posture yet[kf] raw data acc :
```

**Comment by mmurooka** [comment]
+1です. https://github.com/start-jsk/rtmros_tutorials/pull/211#issuecomment-86131164

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1899/
Test PASSed.

**Comment by eisoku9618** [comment]
travis restart by close-and-reopen

**Comment by k-okada** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/1915/
Test PASSed.

**Comment by eisoku9618** [comment]
travis restart by close-and-reopen

**Comment by k-okada** [comment]
@fkanehiro こちらもおねがいします．

**Pull request merged**
